try:
    result = 54/0
except:
    print("error happaned ")
finally:
    print("again here")
